### ISSUE TITLE
append to end as opposed to add a new note

### ISSUE THREAD

**Issue by pcause** [jamesgreenblue/obsidian-quicknote#3]
It would be good to have an option to append to the end of the note specified by the setting instead of creating a new note.  This handles the use case of a quick to do, saving as url, someone's email, etc.  Things that are short text items.

**Comment by jamesgreenblue** [comment]
Hi @pcause,

This plug-in is intentionally minimal for ease of use and speed – I don't have plans currently to expand the functionality.

You're obviously very welcome to fork the code and adapt it to append to an existing note, good luck to you if you decide to do this.
