### ISSUE TITLE
Note creating new note... 

### ISSUE THREAD

**Issue by Superelmanu** [jamesgreenblue/obsidian-quicknote#4]
Hi,
Every time I create a new quick note it opens a new window but without a tab. If I'm in the default theme, it shows me a new note or open note, but it does not create a note. 

Best
M

**Comment by jamesgreenblue** [comment]
Hi @Superelmanu, I'm not able to reproduce this. 

When using this plug-in you should see a window that looks like the screenshot below:

<img width="1136" alt="image" src="https://github.com/jamesgreenblue/obsidian-quicknote/assets/6577312/998165ae-e245-4c5a-8993-837d1e59294f">

The note file will be created in the location where you have told Obsidian to create notes so perhaps check your settings? 

Can I ask you to try the plugin in the Obsidian Sandbox without any other plugins and let me know if you still experience this issue.

**Comment by jamesgreenblue** [comment]
Out of interest, did you change the 'Quick note title' setting? An invalid title setting can prevent notes from being created by Obsidian. 

Ideally if you can share a screenshot of the console output showing any errors would help me to debug this for you.

**Comment by Superelmanu** [comment]
It is working now. I believe it has something to do with the minimal themes or something. I removed it and it's working.
One idea: It will be great to have templates associated to shortcuts for quicknote.

Best
Manu
________________________________

**Comment by jamesgreenblue** [comment]
Glad to hear that it is working.

Please can you make a separate issue for your idea with more detail of how it would work. I'm capacity constrained at the moment so can't make any promises, but at least by documenting the feature it is there for me or someone else to pick up and implement at some point in the future. Contributions are welcome!
